
CFLAGS := -g

all:
	(make square || true)
	(make cube || true)

square: square-main.o square.o
	gcc $(CFLAGS) -o square square-main.o square.o

square-main.o: square-main.c
	gcc $(CFLAGS) -c -o square-main.o square-main.c

square.o: square.s
	gcc $(CFLAGS) -c -o square.o square.s

cube: cube-main.o cube.o
	gcc $(CFLAGS) -o cube cube-main.o cube.o

cube-main.o:
	gcc $(CFLAGS) -c -o cube-main.o cube-main.c

cube.o: cube.s
	gcc $(CFLAGS) -c -o cube.o cube.s

html: hw01.html

hw01.html:
	pandoc -o hw01.html hw01.md

clean:
	rm -f hw01.html *.o square cube

.PHONY: all clean html
